import {
  ArrowsLeftRight,
  CloudArrowDown,
  Database,
  GearSix,
  Globe,
  HardDrives,
  Lightning,
  ShieldCheck,
  Stack,
  TreeStructure,
} from "@phosphor-icons/react";

import type {
  PortfolioStage,
  ProjectData,
  SystemBand,
  SystemEdgeData,
  SystemEdgeKind,
  SystemNodeData,
  TrafficScenario,
} from "./portfolio.types";

export const projectSlots: ProjectData[] = [
  {
    id: "featured-project",
    status: "complete",
    placeholderTitle: "Featured project",
    tags: [],
    images: [],
  },
  {
    id: "currently-working-on",
    status: "in_progress",
    placeholderTitle: "Currently working on",
    tags: [],
    images: [],
  },
  {
    id: "additional-project",
    status: "complete",
    placeholderTitle: "Additional project",
    tags: [],
    images: [],
  },
];

export const resume = {
  education: {
    school: "University of Utah",
    location: "Salt Lake City, UT",
    degree: "Bachelor of Science in Computer Science",
    details: ["Minor in Japanese", "Undergraduate Certificate in Data Science"],
    graduation: "Expected December 2026",
    gpa: "3.746 GPA",
  },
  skills: [
    {
      label: "Languages",
      values: ["Rust", "C++", "C#", "Python", "Java", "TypeScript", "HTML", "CSS"],
    },
    {
      label: "Frameworks + tools",
      values: [
        "React",
        "Next.js",
        "Flutter",
        "Tailwind CSS",
        "PostgreSQL",
        "PyTorch",
        "Docker",
        "Git",
        "Qt Creator",
        "LaTeX",
        "Blazor",
      ],
    },
    {
      label: "Specialties",
      values: [
        "Backend development",
        "Full-stack engineering",
        "Concurrency",
        "High-performance systems",
        "API design",
        "Data structures",
        "Machine learning integration",
      ],
    },
  ],
  certification:
    "Certified Member, National Society of Leadership and Success (NSLS)",
} as const;

export const stageBand: Record<PortfolioStage, SystemBand> = {
  hero: "request",
  projects: "data",
  resume: "ops",
  contact: "ops",
};

export const edgeColors: Record<SystemEdgeKind, string> = {
  request: "#FF8F40",
  response: "#95E6CB",
  data: "#59C2FF",
  async: "#E6B450",
  ops: "#B79CFF",
};

export const systemNodes: SystemNodeData[] = [
  {
    id: "browser",
    title: "Web Browser",
    subtitle: "User request",
    icon: Globe,
    kind: "client",
    band: "request",
    stage: "hero",
    x: 72,
    y: 48,
    language: "ts",
    code: `const request = new Request(
  "/api/profile",
);`,
    initiallyExpanded: true,
  },
  {
    id: "react_view",
    title: "React View",
    subtitle: "Render + events",
    icon: Globe,
    kind: "client",
    band: "request",
    stage: "hero",
    x: 28,
    y: 48,
    language: "ts",
    code: `const profile = useProfile();
return <Hero {...profile} />;`,
    initiallyExpanded: true,
  },
  {
    id: "api_client",
    title: "API Client",
    subtitle: "Typed JSON",
    icon: ArrowsLeftRight,
    kind: "client",
    band: "request",
    stage: "hero",
    x: 28,
    y: 224,
    language: "ts",
    code: `const data = await api.get<Profile>(
  "/profile",
);`,
    initiallyExpanded: true,
  },
  {
    id: "edge_proxy",
    title: "Edge Proxy",
    subtitle: "TLS + policy",
    icon: TreeStructure,
    kind: "service",
    band: "request",
    stage: "hero",
    x: 72,
    y: 224,
    language: "nginx",
    code: `location /api/ {
  proxy_pass http://portfolio;
}`,
    initiallyExpanded: true,
  },
  {
    id: "api_router",
    title: "API Router",
    subtitle: "Axum HTTP",
    icon: TreeStructure,
    kind: "service",
    band: "request",
    stage: "hero",
    x: 72,
    y: 400,
    language: "rust",
    code: `Router::new()
  .route("/profile", get(profile))`,
    initiallyExpanded: true,
  },
  {
    id: "auth_guard",
    title: "Auth Guard",
    subtitle: "JWT / RBAC",
    icon: ShieldCheck,
    kind: "service",
    band: "request",
    stage: "hero",
    x: 28,
    y: 400,
    language: "rust",
    code: `let claims = token.verify()?;
claims.require(Role::Reader)?;`,
    initiallyExpanded: true,
  },
  {
    id: "profile_ingress",
    title: "profile.rs",
    subtitle: "Service boundary",
    icon: Database,
    kind: "core",
    band: "data",
    stage: "projects",
    x: 50,
    y: 52,
    language: "rust",
    code: `pub async fn profile(
  State(app): State<App>,
) -> Json<Profile>`,
    initiallyExpanded: true,
  },
  {
    id: "repository",
    title: "Repository",
    subtitle: "Persistence",
    icon: Database,
    kind: "service",
    band: "data",
    stage: "projects",
    x: 50,
    y: 252,
    language: "rust",
    code: `let profile = repo
  .find_profile(user_id)
  .await?;`,
    initiallyExpanded: true,
  },
  {
    id: "redis",
    title: "Redis Cache",
    subtitle: "Read-through",
    icon: Lightning,
    kind: "data",
    band: "data",
    stage: "projects",
    x: 28,
    y: 456,
    language: "rust",
    code: `cache.get(key).await?
  .map(Profile::decode)`,
    initiallyExpanded: true,
  },
  {
    id: "postgres",
    title: "PostgreSQL",
    subtitle: "Source of truth",
    icon: HardDrives,
    kind: "data",
    band: "data",
    stage: "projects",
    x: 72,
    y: 456,
    language: "sql",
    code: `SELECT name, degree
FROM profiles
WHERE id = $1;`,
    initiallyExpanded: true,
  },
  {
    id: "queue",
    title: "Job Queue",
    subtitle: "Durable broker",
    icon: Stack,
    kind: "data",
    band: "data",
    stage: "projects",
    x: 28,
    y: 680,
    language: "rust",
    code: `queue.publish(
  Job::ProcessMedia(asset),
).await?;`,
    initiallyExpanded: true,
  },
  {
    id: "worker",
    title: "Media Worker",
    subtitle: "Async consumer",
    icon: GearSix,
    kind: "service",
    band: "data",
    stage: "projects",
    x: 72,
    y: 680,
    language: "rust",
    code: `while let Some(job) = rx.recv().await {
  process(job).await?;
}`,
    initiallyExpanded: true,
  },
  {
    id: "object_store",
    title: "Object Store",
    subtitle: "Processed media",
    icon: CloudArrowDown,
    kind: "data",
    band: "data",
    stage: "projects",
    x: 50,
    y: 904,
    language: "rust",
    code: `store.put(
  asset.key(), output,
).await?;`,
    initiallyExpanded: true,
  },
  {
    id: "ci_deploy",
    title: "CI / Deploy",
    subtitle: "Build + release",
    icon: GearSix,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 28,
    y: 52,
    language: "yaml",
    code: `jobs:
  deploy:
    runs-on: ubuntu-latest`,
    initiallyExpanded: true,
  },
  {
    id: "cdn",
    title: "CDN",
    subtitle: "Static assets",
    icon: CloudArrowDown,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 72,
    y: 52,
    language: "nginx",
    code: `location /assets/ {
  expires 1y;
}`,
    initiallyExpanded: true,
  },
  {
    id: "ops_router",
    title: "API Router",
    subtitle: "Runtime traces",
    icon: TreeStructure,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 28,
    y: 276,
    language: "rust",
    code: `#[instrument(skip(state))]
async fn route(state: AppState)`,
    initiallyExpanded: true,
  },
  {
    id: "ops_view",
    title: "React View",
    subtitle: "Client events",
    icon: Globe,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 72,
    y: 276,
    language: "ts",
    code: `telemetry.emit("profile_view", {
  source: "portfolio",
});`,
    initiallyExpanded: true,
  },
  {
    id: "ops_worker",
    title: "Media Worker",
    subtitle: "Job metrics",
    icon: GearSix,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 28,
    y: 500,
    language: "rust",
    code: `metrics::counter!("jobs.completed")
  .increment(1);`,
    initiallyExpanded: true,
  },
  {
    id: "observability",
    title: "Observability",
    subtitle: "Logs + metrics + traces",
    icon: Globe,
    kind: "ops",
    band: "ops",
    stage: "resume",
    x: 72,
    y: 704,
    language: "yaml",
    code: `services:
  collector:
    image: otel/opentelemetry`,
    initiallyExpanded: true,
  },
];

export const systemEdges: SystemEdgeData[] = [
  {
    id: "browser-view",
    from: "browser",
    fromSide: "left",
    to: "react_view",
    toSide: "right",
    kind: "request",
    band: "request",
  },
  {
    id: "view-client",
    from: "react_view",
    fromSide: "bottom",
    to: "api_client",
    toSide: "top",
    kind: "request",
    band: "request",
    label: "fetch",
  },
  {
    id: "client-edge",
    from: "api_client",
    fromSide: "right",
    to: "edge_proxy",
    toSide: "left",
    kind: "request",
    band: "request",
    label: "HTTPS",
  },
  {
    id: "edge-router",
    from: "edge_proxy",
    fromSide: "bottom",
    to: "api_router",
    toSide: "top",
    kind: "request",
    band: "request",
  },
  {
    id: "router-auth",
    from: "api_router",
    fromSide: "left",
    to: "auth_guard",
    toSide: "right",
    kind: "request",
    band: "request",
  },
  {
    id: "auth-profile",
    from: "auth_guard",
    fromSide: "bottom",
    to: "profile_ingress",
    toSide: "top",
    kind: "request",
    band: "request",
    label: "authorized",
  },
  {
    id: "profile-router-response",
    from: "profile_ingress",
    fromSide: "top",
    to: "api_router",
    toSide: "bottom",
    kind: "response",
    band: "request",
    label: "200 JSON",
  },
  {
    id: "router-edge-response",
    from: "api_router",
    fromSide: "top",
    to: "edge_proxy",
    toSide: "bottom",
    kind: "response",
    band: "request",
  },
  {
    id: "edge-client-response",
    from: "edge_proxy",
    fromSide: "left",
    to: "api_client",
    toSide: "right",
    kind: "response",
    band: "request",
  },
  {
    id: "client-view-response",
    from: "api_client",
    fromSide: "top",
    to: "react_view",
    toSide: "bottom",
    kind: "response",
    band: "request",
  },
  {
    id: "view-browser-response",
    from: "react_view",
    fromSide: "right",
    to: "browser",
    toSide: "left",
    kind: "response",
    band: "request",
  },
  {
    id: "profile-repository",
    from: "profile_ingress",
    fromSide: "bottom",
    to: "repository",
    toSide: "top",
    kind: "data",
    band: "data",
    label: "CRUD",
  },
  {
    id: "repository-redis",
    from: "repository",
    fromSide: "bottom",
    to: "redis",
    toSide: "top",
    kind: "data",
    band: "data",
    label: "cache",
  },
  {
    id: "repository-postgres",
    from: "repository",
    fromSide: "bottom",
    to: "postgres",
    toSide: "top",
    kind: "data",
    band: "data",
    label: "SQL",
  },
  {
    id: "profile-queue",
    from: "profile_ingress",
    fromSide: "right",
    to: "queue",
    toSide: "top",
    kind: "async",
    band: "data",
    label: "enqueue",
  },
  {
    id: "queue-worker",
    from: "queue",
    fromSide: "right",
    to: "worker",
    toSide: "left",
    kind: "async",
    band: "data",
  },
  {
    id: "worker-store",
    from: "worker",
    fromSide: "bottom",
    to: "object_store",
    toSide: "top",
    kind: "async",
    band: "data",
  },
  {
    id: "deploy-cdn",
    from: "ci_deploy",
    fromSide: "right",
    to: "cdn",
    toSide: "left",
    kind: "ops",
    band: "ops",
    label: "assets",
  },
  {
    id: "deploy-router",
    from: "ci_deploy",
    fromSide: "bottom",
    to: "ops_router",
    toSide: "top",
    kind: "ops",
    band: "ops",
    label: "release",
  },
  {
    id: "router-observe",
    from: "ops_router",
    fromSide: "right",
    to: "observability",
    toSide: "left",
    kind: "ops",
    band: "ops",
    label: "traces",
  },
  {
    id: "view-observe",
    from: "ops_view",
    fromSide: "bottom",
    to: "observability",
    toSide: "top",
    kind: "ops",
    band: "ops",
    label: "events",
  },
  {
    id: "worker-observe",
    from: "ops_worker",
    fromSide: "right",
    to: "observability",
    toSide: "left",
    kind: "ops",
    band: "ops",
    label: "metrics",
  },
];

export const trafficScenarios: TrafficScenario[] = [
  {
    id: "profile-request",
    band: "request",
    weight: 1,
    steps: [
      { edgeIds: ["browser-view"] },
      { edgeIds: ["view-client"] },
      { edgeIds: ["client-edge"] },
      { edgeIds: ["edge-router"] },
      { edgeIds: ["router-auth"] },
      { edgeIds: ["auth-profile"] },
      { edgeIds: ["profile-router-response"], pauseMs: 160 },
      { edgeIds: ["router-edge-response"] },
      { edgeIds: ["edge-client-response"] },
      { edgeIds: ["client-view-response"] },
      { edgeIds: ["view-browser-response"] },
    ],
  },
  {
    id: "cache-read",
    band: "data",
    weight: 3,
    steps: [
      { edgeIds: ["profile-repository"] },
      { edgeIds: ["repository-redis"], pauseMs: 180 },
      { edgeIds: [], reverseEdgeIds: ["repository-redis"] },
      { edgeIds: [], reverseEdgeIds: ["profile-repository"] },
    ],
  },
  {
    id: "database-read",
    band: "data",
    weight: 2,
    steps: [
      { edgeIds: ["profile-repository"] },
      { edgeIds: ["repository-postgres"], pauseMs: 220 },
      { edgeIds: [], reverseEdgeIds: ["repository-postgres"] },
      { edgeIds: [], reverseEdgeIds: ["profile-repository"] },
    ],
  },
  {
    id: "media-job",
    band: "data",
    weight: 1.5,
    steps: [
      { edgeIds: ["profile-queue"] },
      { edgeIds: ["queue-worker"] },
      { edgeIds: ["worker-store"] },
    ],
  },
  {
    id: "release",
    band: "ops",
    weight: 1.5,
    steps: [
      { edgeIds: ["deploy-cdn", "deploy-router"] },
      { edgeIds: ["router-observe"] },
    ],
  },
  {
    id: "telemetry",
    band: "ops",
    weight: 2,
    steps: [
      { edgeIds: ["router-observe", "view-observe", "worker-observe"] },
    ],
  },
];
