import {
  ArrowsLeftRight,
  CloudArrowDown,
  Database,
  GearSix,
  Globe,
  HardDrives,
  Lightning,
  ShieldCheck,
  Stack,
  TreeStructure,
} from "@phosphor-icons/react";

import type {
  PortfolioStage,
  ProjectData,
  SystemBand,
  SystemEdgeData,
  SystemEdgeKind,
  SystemNodeData,
  TrafficScenario,
} from "./portfolio.types";

export const projectSlots: ProjectData[] = [
  {
    id: "featured-project",
    status: "complete",
    placeholderTitle: "Featured project",
    tags: [],
    images: [],
  },
  {
    id: "currently-working-on",
    status: "in_progress",
    placeholderTitle: "Currently working on",
    tags: [],
    images: [],
  },
  {
    id: "additional-project",
    status: "complete",
    placeholderTitle: "Additional project",
    tags: [],
    images: [],
  },
];

export const resume = {
  education: {
    school: "University of Utah",
    location: "Salt Lake City, UT",
    degree: "Bachelor of Science in Computer Science",
    details: ["Minor in Japanese", "Undergraduate Certificate in Data Science"],
    graduation: "Expected December 2026",
    gpa: "3.746 GPA",
  },
  skills: [
    {
      label: "Languages",
      values: ["Rust", "C++", "C#", "Python", "Java", "TypeScript", "HTML", "CSS"],
    },
    {
      label: "Frameworks + tools",
      values: [
        "React",
        "Next.js",
        "Flutter",
        "Tailwind CSS",
        "PostgreSQL",
        "PyTorch",
        "Docker",
        "Git",
        "Qt Creator",
        "LaTeX",
        "Blazor",
      ],
    },
    {
      label: "Specialties",
      values: [
        "Backend development",
        "Full-stack engineering",
        "Concurrency",
        "High-performance systems",
        "API design",
        "Data structures",
        "Machine learning integration",
      ],
    },
  ],
  certification:
    "Certified Member, National Society of Leadership and Success (NSLS)",
} as const;

export const SYSTEM_CANVAS_HEIGHT = 2180;

export const stageBand: Record<PortfolioStage, SystemBand> = {
  hero: "request",
  projects: "data",
  resume: "ops",
  contact: "ops",
};

export const stageAnchor: Record<PortfolioStage, number> = {
  hero: 280,
  projects: 930,
  resume: 1710,
  contact: 1880,
};

export const edgeColors: Record<SystemEdgeKind, string> = {
  request: "#FF8F40",
  response: "#95E6CB",
  data: "#59C2FF",
  async: "#E6B450",
  ops: "#B79CFF",
};

export const systemNodes: SystemNodeData[] = [
  {
    id: "browser",
    title: "Web Browser",
    subtitle: "User request",
    icon: Globe,
    kind: "client",
    band: "request",
    x: 72,
    y: 78,
  },
  {
    id: "react_view",
    title: "React View",
    subtitle: "Render + events",
    icon: Globe,
    kind: "client",
    band: "request",
    x: 28,
    y: 78,
  },
  {
    id: "api_client",
    title: "API Client",
    subtitle: "Typed JSON",
    icon: ArrowsLeftRight,
    kind: "client",
    band: "request",
    x: 28,
    y: 226,
  },
  {
    id: "edge_proxy",
    title: "Edge Proxy",
    subtitle: "TLS + policy",
    icon: TreeStructure,
    kind: "service",
    band: "request",
    x: 72,
    y: 226,
  },
  {
    id: "api_router",
    title: "API Router",
    subtitle: "Axum HTTP",
    icon: TreeStructure,
    kind: "service",
    band: "request",
    x: 72,
    y: 374,
  },
  {
    id: "auth_guard",
    title: "Auth Guard",
    subtitle: "JWT / RBAC",
    icon: ShieldCheck,
    kind: "service",
    band: "request",
    x: 28,
    y: 374,
  },
  {
    id: "profile_ingress",
    title: "profile.rs",
    subtitle: "Service boundary",
    icon: Database,
    kind: "core",
    band: "data",
    x: 50,
    y: 654,
  },
  {
    id: "repository",
    title: "Repository",
    subtitle: "Persistence",
    icon: Database,
    kind: "service",
    band: "data",
    x: 28,
    y: 812,
  },
  {
    id: "redis",
    title: "Redis Cache",
    subtitle: "Read-through",
    icon: Lightning,
    kind: "data",
    band: "data",
    x: 72,
    y: 748,
  },
  {
    id: "postgres",
    title: "PostgreSQL",
    subtitle: "Source of truth",
    icon: HardDrives,
    kind: "data",
    band: "data",
    x: 72,
    y: 900,
  },
  {
    id: "queue",
    title: "Job Queue",
    subtitle: "Durable broker",
    icon: Stack,
    kind: "data",
    band: "data",
    x: 28,
    y: 1050,
  },
  {
    id: "worker",
    title: "Media Worker",
    subtitle: "Async consumer",
    icon: GearSix,
    kind: "service",
    band: "data",
    x: 72,
    y: 1050,
  },
  {
    id: "object_store",
    title: "Object Store",
    subtitle: "Processed media",
    icon: CloudArrowDown,
    kind: "data",
    band: "data",
    x: 72,
    y: 1196,
  },
  {
    id: "ci_deploy",
    title: "CI / Deploy",
    subtitle: "Build + release",
    icon: GearSix,
    kind: "ops",
    band: "ops",
    x: 28,
    y: 1490,
  },
  {
    id: "cdn",
    title: "CDN",
    subtitle: "Static assets",
    icon: CloudArrowDown,
    kind: "ops",
    band: "ops",
    x: 72,
    y: 1490,
  },
  {
    id: "ops_router",
    title: "API Router",
    subtitle: "Runtime traces",
    icon: TreeStructure,
    kind: "ops",
    band: "ops",
    x: 28,
    y: 1640,
  },
  {
    id: "ops_view",
    title: "React View",
    subtitle: "Client events",
    icon: Globe,
    kind: "ops",
    band: "ops",
    x: 72,
    y: 1640,
  },
  {
    id: "ops_worker",
    title: "Media Worker",
    subtitle: "Job metrics",
    icon: GearSix,
    kind: "ops",
    band: "ops",
    x: 28,
    y: 1790,
  },
  {
    id: "observability",
    title: "Observability",
    subtitle: "Logs + metrics + traces",
    icon: Globe,
    kind: "ops",
    band: "ops",
    x: 72,
    y: 1870,
  },
];

export const systemEdges: SystemEdgeData[] = [
  { id: "browser-view", from: "browser", fromSide: "left", to: "react_view", toSide: "right", kind: "request", band: "request" },
  { id: "view-client", from: "react_view", fromSide: "bottom", to: "api_client", toSide: "top", kind: "request", band: "request", label: "fetch" },
  { id: "client-edge", from: "api_client", fromSide: "right", to: "edge_proxy", toSide: "left", kind: "request", band: "request", label: "HTTPS" },
  { id: "edge-router", from: "edge_proxy", fromSide: "bottom", to: "api_router", toSide: "top", kind: "request", band: "request" },
  { id: "router-auth", from: "api_router", fromSide: "left", to: "auth_guard", toSide: "right", kind: "request", band: "request" },
  { id: "auth-profile", from: "auth_guard", fromSide: "bottom", to: "profile_ingress", toSide: "top", kind: "request", band: "request", label: "authorized" },
  { id: "profile-repository", from: "profile_ingress", fromSide: "bottom", to: "repository", toSide: "top", kind: "data", band: "data", label: "CRUD" },
  { id: "repository-redis", from: "repository", fromSide: "right", to: "redis", toSide: "left", kind: "data", band: "data", label: "cache" },
  { id: "repository-postgres", from: "repository", fromSide: "right", to: "postgres", toSide: "left", kind: "data", band: "data", label: "SQL" },
  { id: "profile-queue", from: "profile_ingress", fromSide: "right", to: "queue", toSide: "top", kind: "async", band: "data", label: "enqueue" },
  { id: "queue-worker", from: "queue", fromSide: "right", to: "worker", toSide: "left", kind: "async", band: "data" },
  { id: "worker-store", from: "worker", fromSide: "bottom", to: "object_store", toSide: "top", kind: "async", band: "data" },
  { id: "deploy-cdn", from: "ci_deploy", fromSide: "right", to: "cdn", toSide: "left", kind: "ops", band: "ops", label: "assets" },
  { id: "deploy-router", from: "ci_deploy", fromSide: "bottom", to: "ops_router", toSide: "top", kind: "ops", band: "ops", label: "release" },
  { id: "router-observe", from: "ops_router", fromSide: "right", to: "observability", toSide: "left", kind: "ops", band: "ops", label: "traces" },
  { id: "view-observe", from: "ops_view", fromSide: "bottom", to: "observability", toSide: "top", kind: "ops", band: "ops", label: "events" },
  { id: "worker-observe", from: "ops_worker", fromSide: "right", to: "observability", toSide: "left", kind: "ops", band: "ops", label: "metrics" },
];

export const trafficScenarios: TrafficScenario[] = [
  {
    id: "profile-request",
    band: "request",
    weight: 1,
    steps: [
      { edgeIds: ["browser-view"] },
      { edgeIds: ["view-client"] },
      { edgeIds: ["client-edge"] },
      { edgeIds: ["edge-router"] },
      { edgeIds: ["router-auth"] },
      { edgeIds: ["auth-profile"] },
    ],
  },
  {
    id: "cache-read",
    band: "data",
    weight: 3,
    steps: [
      { edgeIds: ["profile-repository"] },
      { edgeIds: ["repository-redis"], pauseMs: 180 },
      { edgeIds: [], reverseEdgeIds: ["repository-redis"] },
      { edgeIds: [], reverseEdgeIds: ["profile-repository"] },
    ],
  },
  {
    id: "database-read",
    band: "data",
    weight: 2,
    steps: [
      { edgeIds: ["profile-repository"] },
      { edgeIds: ["repository-postgres"], pauseMs: 220 },
      { edgeIds: [], reverseEdgeIds: ["repository-postgres"] },
      { edgeIds: [], reverseEdgeIds: ["profile-repository"] },
    ],
  },
  {
    id: "media-job",
    band: "data",
    weight: 1.5,
    steps: [
      { edgeIds: ["profile-queue"] },
      { edgeIds: ["queue-worker"] },
      { edgeIds: ["worker-store"] },
    ],
  },
  {
    id: "release",
    band: "ops",
    weight: 1.5,
    steps: [
      { edgeIds: ["deploy-cdn", "deploy-router"] },
      { edgeIds: ["router-observe"] },
    ],
  },
  {
    id: "telemetry",
    band: "ops",
    weight: 2,
    steps: [
      { edgeIds: ["router-observe", "view-observe", "worker-observe"] },
    ],
  },
];
